# Generated by Django 5.1.7 on 2025-03-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(max_length=200)),
                ('model_name', models.CharField(choices=[('Q2_K', 'Q2_K'), ('Q3_K_S', 'Q3_K_S'), ('Q3_K_M', 'Q3_K_M'), ('Q4_0', 'Q4_0'), ('Q4_K_S', 'Q4_K_S'), ('Q4_K_M', 'Q4_K_M'), ('Q5_0', 'Q5_0'), ('Q5_1', 'Q5_1'), ('Q5_K_M', 'Q5_K_M'), ('Q6_K', 'Q6_K'), ('Q8_0', 'Q8_0')], default='Q4_K_M', max_length=200)),
                ('version_tag', models.CharField(default='latest', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
