# Generated by Django 5.1.7 on 2025-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_tool_llmconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llm',
            name='internal_name',
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='internal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='tools',
            field=models.ManyToManyField(to='ai.tool'),
        ),
        migrations.AddField(
            model_name='tool',
            name='version',
            field=models.CharField(default='1.0', max_length=200),
        ),
    ]
