# Generated by Django 5.1.7 on 2025-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_llm_internal_name_llmconfig_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='model_quantization',
            field=models.CharField(choices=[('Q2_K', 'Q2_K'), ('Q3_K_S', 'Q3_K_S'), ('Q3_K_M', 'Q3_K_M'), ('Q4_0', 'Q4_0'), ('Q4_K_S', 'Q4_K_S'), ('Q4_K_M', 'Q4_K_M'), ('Q5_0', 'Q5_0'), ('Q5_1', 'Q5_1'), ('Q5_K_M', 'Q5_K_M'), ('Q6_K', 'Q6_K'), ('Q8_0', 'Q8_0')], default='Q4_K_M', max_length=10),
        ),
        migrations.AlterField(
            model_name='llm',
            name='model_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
